import { expect, test } from "@playwright/test";
import { randomBytes, randomUUID } from "node:crypto";
import { keccak256 } from "viem";
import QRCode from "qrcode";
import { createIdentityEnv, createPublicationLinkEnv } from "../../src/config/env";
import { settledFixture, sql } from "../../src/lib/db/settlement.test-support";
import { createReceiptRepository } from "../../src/lib/db/receipts";
import { publicationLink } from "../../src/lib/invoices/publication-links";
import { createKeyedTokenCodec } from "../../src/lib/security/keyed-token";
import { inspectInvoicePdf } from "../../src/lib/documents/pdf-verification";
import { createSessionCodec } from "../../src/lib/auth/session";
import { SESSION_COOKIE } from "../../src/lib/identity/contracts";

test.use({ trace: "off", video: "off", screenshot: "off" });
test.setTimeout(180_000);

async function protectedFetch(url: string, headers: Record<string, string> = {}) {
  try {
    const response = await fetch(url, { headers, redirect: "manual" });
    if (response.status !== 307) return response;
    const next = new URL(response.headers.get("location") ?? "", url), original = new URL(url);
    if (!headers.RSC || next.origin !== original.origin || next.pathname !== original.pathname || !next.searchParams.has("_rsc")) throw new Error();
    return await fetch(next, { headers, redirect: "manual" });
  } catch { throw new Error("Protected receipt request failed"); }
}

async function readyReceipt(baseURL: string) {
  if (new URL(baseURL).hostname !== "localhost" || baseURL !== process.env.NEXT_PUBLIC_APP_URL) throw new Error("Local compiled receipt tests only");
  const config = createPublicationLinkEnv();
  // Frozen invoice/event facts are synthetic fixtures. The receipt is generated by the real compiled HTTP worker.
  const identity = { workspaceId: randomUUID(), ownerWallet: `0x${randomBytes(20).toString("hex")}` };
  sql(`begin; insert into public.workspaces(id,owner_wallet) values('${identity.workspaceId}','${identity.ownerWallet}');
    insert into public.sender_profiles(id,workspace_id,payout_wallet) values('${identity.workspaceId}','${identity.workspaceId}','${identity.ownerWallet}'); commit;`);
  const fixture = await settledFixture(true, config.keys, 1, identity);
  const receipts = createReceiptRepository(fixture.db);
  for (let pass = 0; pass < 20; pass++) {
    const ready = await receipts.read(fixture.receiptTokenId);
    if (ready) return { ...fixture, ready, config, url: publicationLink(ready.link, "receipt-bearer", config) };
    const response = await protectedFetch(`${baseURL}/api/jobs/receipts`, { Authorization: `Bearer ${process.env.CRON_SECRET}` });
    if (!response.ok) throw new Error("Compiled receipt worker failed");
  }
  throw new Error("Receipt fixture was not ready within the bounded worker run");
}

test("receipt: compiled worker serves immutable private PDF/QR proof and preserves owner SSR redaction", async ({ page, context, baseURL }, testInfo) => {
  const fixture = await readyReceipt(baseURL!);
  const { ready, url, config, actor, db } = fixture;
  const secretValues = [ready.id, ready.invoiceId, ready.invoiceVersionId, ready.workspaceId, ready.link.tokenId, ready.link.verifierHash,
    ready.attempt.publicationSalt, ready.attempt.storageKey, "owner@example.test", "client@example.test"];
  const response = await protectedFetch(url);
  expect(response.status).toBe(200);
  expect(response.headers.get("cache-control")).toContain("no-store");
  expect(response.headers.get("referrer-policy")).toBe("no-referrer");
  const html = await response.text();
  expect(secretValues.some((value) => html.includes(value))).toBe(false);
  const rsc = await protectedFetch(url, { RSC: "1" });
  expect(rsc.status).toBe(200);
  const rscBody = await rsc.text();
  expect(secretValues.some((value) => rscBody.includes(value))).toBe(false);
  const pdf = await protectedFetch(`${url}/pdf`);
  expect(pdf.status).toBe(200);
  const bytes = new Uint8Array(await pdf.arrayBuffer());
  expect(keccak256(bytes) === ready.artifact!.pdfContentHash).toBe(true);
  const inspection = await inspectInvoicePdf(bytes);
  expect(inspection.qrDestinations.length === 1 && inspection.qrDestinations[0] === url).toBe(true);
  expect(inspection.text.includes(ready.settlement.transactionHash)).toBe(true);
  const again = await protectedFetch(`${baseURL}/api/jobs/receipts`, { Authorization: `Bearer ${process.env.CRON_SECRET}` });
  expect(again.status).toBe(200);
  const reread = (await createReceiptRepository(db).read(fixture.receiptTokenId))!;
  expect(reread.artifact!.pdfContentHash === ready.artifact!.pdfContentHash).toBe(true);
  const disabled = await protectedFetch(`${baseURL}/api/jobs/outbox`, { Authorization: `Bearer ${process.env.CRON_SECRET}` });
  expect(await disabled.json()).toEqual({ outcome: "disabled" });

  const session = await createSessionCodec(createIdentityEnv()).seal({ workspaceId: actor.workspaceId, ownerWallet: actor.ownerWallet });
  for (const headers of [{}, { RSC: "1" }] as Record<string, string>[]) {
    const owner = await protectedFetch(`${baseURL}/app/invoices/${ready.invoiceId}`, { ...headers, Cookie: `${SESSION_COOKIE}=${session}` });
    const content = await owner.text();
    expect(owner.status).toBe(200);
    expect(content.includes(new URL(url).pathname.split("/").at(-1)!)).toBe(false);
    expect(content.includes(ready.link.verifierHash)).toBe(false);
    expect(content.includes("Payment verified")).toBe(true);
  }

  await page.goto(baseURL!);
  let passed = false, qr = "";
  try {
    await page.evaluate((destination) => window.location.assign(destination), url);
    await page.getByRole("heading", { name: `Receipt ${ready.attempt.invoiceNumber}`, exact: true }).waitFor({ timeout: 20_000 });
    const checks = await page.evaluate(() => ({ fits: document.documentElement.scrollWidth <= innerWidth,
      qr: document.querySelector<HTMLImageElement>('img[alt="QR code for this protected receipt"]')?.src ?? "",
      nonce: [...document.scripts].every((script) => Boolean(script.nonce)),
      controls: [...document.querySelectorAll("main a")].every((link) => link.getBoundingClientRect().height >= 44) }));
    qr = checks.qr;
    const { createCanvas, loadImage } = await import("@napi-rs/canvas"); const { default: jsQR } = await import("jsqr");
    const image = await loadImage(qr), canvas = createCanvas(image.width, image.height), canvasContext = canvas.getContext("2d");
    canvasContext.drawImage(image, 0, 0);
    const decoded = jsQR(new Uint8ClampedArray(canvasContext.getImageData(0, 0, image.width, image.height).data), image.width, image.height);
    const download = page.getByRole("link", { name: "Download receipt PDF" }); await download.focus();
    const focus = await download.evaluate((element) => getComputedStyle(element).outlineStyle !== "none");
    passed = checks.fits && checks.nonce && checks.controls && focus && decoded?.data === url;
  } catch { /* Retain only boolean failure evidence, not a credential-bearing locator dump. */ }
  finally { await page.close(); }
  expect(passed).toBe(true);

  // Visual review uses the actual HTML with all credential-bearing script/QR/link material replaced before rendering.
  const inertQr = await QRCode.toDataURL(`${baseURL}/receipt/visual-only.not-a-credential`, { width: 600, margin: 4 });
  const slug = new URL(url).pathname.split("/").at(-1)!;
  expect(Boolean(qr) && html.includes(qr)).toBe(true);
  const inertHtml = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "").replaceAll(qr, inertQr).replaceAll(slug, "visual-only.not-a-credential");
  const preview = await context.newPage();
  await preview.goto(baseURL!); await preview.setContent(inertHtml); await preview.screenshot({ path: testInfo.outputPath("receipt-safe.png"), fullPage: true }); await preview.close();

  const wrong = createKeyedTokenCodec(config.keys).derive(ready.link.tokenId, "invoice-bearer", ready.link.keyVersion).slug;
  expect((await protectedFetch(`${baseURL}/receipt/${wrong}`)).status).toBe(404);
  sql(`update public.access_links set revoked_at=clock_timestamp() where token_id='${ready.link.tokenId}';`);
  for (const suffix of ["", "/pdf"]) {
    for (const headers of [{}, { RSC: "1" }, { RSC: "1", "Next-Router-Prefetch": "1" }] as Record<string, string>[]) {
      const denied = await protectedFetch(`${url}${suffix}`, headers);
      expect(denied.status).toBe(404); expect(denied.headers.get("cache-control")).toContain("no-store");
    }
  }
});
